### ISSUE TITLE
Snippets never load

### ISSUE THREAD

**Issue by logix2** [mikebarkmin/ulauncher-snippets#10]
I'm using Ulauncher 5.11 with the snippets extension, and using some test snippets from this GitHub repository, the snippets don't load. All I get after typing "snip " is "Loading", but the snippets never load.

And one more thing. By default, the snippets directory is set to ~/snippets. But it appears the Snippets extension doesn't convert ``~`` to ``/home/$USER`` because placing the snippets in ~/snippets, typing "snip " in Ulauncher returns "No snippet". After entering the full path to the snippets folder (e.g. /home/logix/snippets) in the extension settings, the "No snippet" message was gone, but now I'm stuck at the but I mentioned above.

**Comment by jlimas** [comment]
Not sure if you were having the same issue as me but the snippets need to have the .j2 extension

Also make sure you install the required dependencies and if you are using ubuntu 20 with wayland change the snippets copy mode to Wayland Clipboard Mode :smile:

**Comment by WebInspectInc** [comment]
I was having this exact problem, but then I re-ran the pip3 command (`pip3 install --user dateparser jinja2 python-frontmatter`), rebooted ulauncher, and that fixed it. I would guess that one of the dependencies didn't get installed correctly the first time, so the plugin failed silently. Just FYI.

**Comment by mikebarkmin** [comment]
Thanks for giving the right instructions. I really hope Ulauncher implements a way to automatically install dependencies. https://github.com/Ulauncher/Ulauncher/issues/273

**Comment by dipeshsingh253** [comment]
Thanks [jlimas](https://github.com/jlimas) and [WebInspectInc](https://github.com/WebInspectInc) your suggestions worked for me.
