### ISSUE TITLE
More doc

### ISSUE THREAD

**Issue by daladim** [mikebarkmin/ulauncher-snippets#3]
Hi,

I can't understand how to use your plugin (yet it looks terrific).

I'd like to create a veeeery simple, one-line, static text snippet, but I don't understand how to do so.

I've read the readme, but it only describes more complex use-cases. I tried to create `~/.config/snippets/stuff.j2` with some `name` and `description` headers, but snip still says "No snippet" (of course I have changed the snippets directory in Ulauncher's config)

How could I do? \
I wished putting a single line plain text file in my snippets folder would do the trick, yet it doesn't. \
Event better, maybe you could support a single snippet file where every line is a snippet.

Thanks

**Comment by mikebarkmin** [comment]
Can you try an absolute path by expanding the "~" to "/home/{your_username}"?

**Comment by daladim** [comment]
I've expanded my home path.
It is now slightly different, since I now have a "Loading..." text (that never changes) instead of the "No snippet" that i had before.

Is there any log file I could check or upload in this issue ?

**Comment by mikebarkmin** [comment]
You can start ulauncher from the termina to enable the verbose mode: `ulauncher -v`

**Comment by daladim** [comment]
There is not much in the logs
```
2021-03-23 15:54:53,477 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.mikebarkmin.ulauncher-snippets" connected
2021-03-23 15:54:53,478 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.mikebarkmin.ulauncher-snippets"
2021-03-23 15:54:57,425 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2021-03-23 15:54:57,427 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2021-03-23 15:54:57,474 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
2021-03-23 15:54:57,631 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2021-03-23 15:54:58,097 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.mikebarkmin.ulauncher-snippets"
2021-03-23 15:54:58,298 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
```

My config sets `/home/jerome/.config/snippets` as the snippets directory.
Here is the content of `/home/jerome/.config/snippets/stuff.j2` :
```
---
name: Word Count
description: Count the words in the clipboard.
---
snip snip
```

**Comment by Garvnanwani** [comment]
I am facing the same issue, the moment I click on the snippet  I get a loading text that never goes away

**Comment by Garvnanwani** [comment]
@mikebarkmin can you please have a look at this issue, i am facing the issue as @daladim, so might be others are also facing and there is not other alternative to this

**Comment by mikebarkmin** [comment]
I would really like to solve the issue, but I can not replicate it. You could try using another copy mode. For example xsel or wayland clipboard mode, depending on your system.

**Comment by daladim** [comment]
If that could help replicating, I am using Ubuntu 20.04 with the regular Gnome shell. I could give you a list of the very few Gnome extensions I have installed if you want (I'm not currently in front of my computer).
IIRC, I have tried both X11 and Wayland sessions

**Comment by Garvnanwani** [comment]
https://user-images.githubusercontent.com/36405030/112592223-a6e9a500-8e2b-11eb-83bf-a4ee8daa0305.mp4


Here is the screen record, tried all the three copying methods but none is working

**Comment by zoni** [comment]
I think you're running into a combination of #5 or #6 here.

If any of you wish to verify this prior to my PRs being merged, you can install my fork from https://github.com/zoni/ulauncher-snippets which has fixes for each of these on the main branch.

**Comment by mikebarkmin** [comment]
This is now merged. If the issue still exists, please comment.
